insert into "USER"(ID,NAME,IDCARD) values(1,'AWAGAWRGW4R','FREAR4ATGF4WE');
insert into "USER"(ID,NAME,IDCARD) values(2,'EWAGAWRGW4R','FREGR4ATGF4WE');
insert into "USER"(ID,NAME,IDCARD) values(3,'FWAGAWRGW4R','FRAGR4ATGF4WE');
